# =========================
# Variables - General
# =========================

$mainMod=SUPER

$mainBrowser = zen
$editor = zeditor
$terminal = kitty
$fileManager = nautilus
$menu = noctalia-shell ipc call launcher toggle

# =========================
# Variables - Decor
# =========================

$space = 9

$spaceXs = 2
$spaceSm = 3
$spaceMd = 7
$spaceLg = 9
$spaceXl = 19
