# =========================
# Imports
# =========================

source = ./_vars.conf

# =========================
# Startup
# =========================

exec-once=noctalia-shell

env = XCURSOR_THEME,Sweet-cursors
env = XCURSOR_SIZE,$spaceXl

env = XDG_DATA_DIRS,$HOME/.local/share:$XDG_DATA_DIRS

env = HYPRCURSOR_THEME,
env = HYPRCURSOR_SIZE,

exec-once = hyprctl setcursor Sweet-cursors $spaceXl
