# =========================
# Rules
# =========================

windowrule {
    name = ^(Picture-in-Picture)$
    match:title = ^(Picture-in-Picture)$
    float = true
    center = false
    pin = true
    opacity = 1.0 override 1.0 override
    size = 568 320
    move = monitor_w-420 monitor_h-320
}
